USE [master]
GO

/****** Object:  Database [news_blog]    Script Date: 17-Jun-21 8:13:18 PM ******/
CREATE DATABASE [news_blog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'news_blog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\news_blog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'news_blog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\news_blog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [news_blog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [news_blog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [news_blog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [news_blog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [news_blog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [news_blog] SET ARITHABORT OFF 
GO

ALTER DATABASE [news_blog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [news_blog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [news_blog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [news_blog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [news_blog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [news_blog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [news_blog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [news_blog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [news_blog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [news_blog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [news_blog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [news_blog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [news_blog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [news_blog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [news_blog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [news_blog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [news_blog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [news_blog] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [news_blog] SET  MULTI_USER 
GO

ALTER DATABASE [news_blog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [news_blog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [news_blog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [news_blog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [news_blog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [news_blog] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [news_blog] SET QUERY_STORE = OFF
GO

ALTER DATABASE [news_blog] SET  READ_WRITE 
GO


